//-----------------------------------------------------------------
// TX_TL_Monitor
//   Lives under one Env_Top instance, gets its own env_cfg, and
//   runs the REAL TL-layer monitor logic for whichever role
//   cfg.mode says it is - two concurrent threads per role.
//
//   RC_MODE (real TX_TL_Monitor.sv reference): thread 1 captures
//   outgoing TX requests off TX_TL_DL, thread 2 captures incoming
//   RX completions (with ECRC check) off TX_TL_DL, both published
//   on TX_TL_Send.
//
//   EP_MODE (real RX_TL_Monitor.sv reference): thread 1 captures
//   incoming TX requests off RX_TL_DL (with ECRC check) - this is
//   what feeds RX_PCIe_LUT via RX_TL_MON_Send (wired in Env_Top's
//   connect_phase). Thread 2 captures outgoing completion TLPs
//   generated by the LUT/driver off RX_TL_DL, published on
//   RX_TL_Send.
//
//   The reference project's e_type (tlp_type_e) field was used
//   only for $display debug logging here, never for control flow
//   - per the same fmt/r_type-only design decision used for
//   RX_PCIe_LUT, those debug lines print raw fmt/r_type values
//   instead of decoding to an e_type name.
//-----------------------------------------------------------------
class PCIe_TL_Monitor extends uvm_monitor;

  `uvm_component_utils(PCIe_TL_Monitor)

  env_cfg cfg;
  string  tag;

  //-----------------------------------------------------------
  // Role-specific interface handles
  //-----------------------------------------------------------
  virtual TX_TL_DL_Interface TX_TL_DL;   // RC_MODE
  virtual RX_TL_DL_Interface RX_TL_DL;   // EP_MODE

  //-----------------------------------------------------------
  // RC_MODE analysis port
  //-----------------------------------------------------------
  uvm_analysis_port #(Sequence_item) TX_TL_Send;

  //-----------------------------------------------------------
  // EP_MODE analysis ports
  //   RX_TL_MON_Send specifically feeds RX_PCIe_LUT (wired in
  //   Env_Top's connect_phase to PCIe_LUT.RX_LUT_imp).
  //-----------------------------------------------------------
  uvm_analysis_port #(Sequence_item) RX_TL_Send;
  uvm_analysis_port #(Sequence_item) RX_TL_MON_Send;

  function new(string name = "PCIe_TL_Monitor", uvm_component parent = null);
    super.new(name, parent);
    TX_TL_Send     = new("TX_TL_Send", this);
    RX_TL_Send     = new("RX_TL_Send", this);
    RX_TL_MON_Send = new("RX_TL_MON_Send", this);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);

    if(!uvm_config_db#(env_cfg)::get(this, "", "env_cfg", cfg))
      `uvm_fatal("TX_TL_Monitor", $sformatf("env_cfg not found for %s", get_full_name()))

    tag = get_full_name();
    `uvm_info("TX_TL_Monitor", $sformatf("[%s] Configured: mode=%s", tag, cfg.mode.name()), UVM_HIGH)

    case(cfg.mode)

      RC_MODE: begin
        if(!uvm_config_db#(virtual TX_TL_DL_Interface)::get(this, "", "TL_Vif", TX_TL_DL))
          `uvm_fatal("TX_TL_Monitor", $sformatf("[%s] Unable to access TX_TL_DL interface", tag))
        else
          `uvm_info("TX_TL_Monitor", $sformatf("[%s] Successfully accessed interface", tag), UVM_HIGH)
      end

      EP_MODE: begin
        if(!uvm_config_db#(virtual RX_TL_DL_Interface)::get(this, "", "TL_Vif", RX_TL_DL))
          `uvm_fatal("RX_TL_MONITOR", $sformatf("[%s] Unable to access RX TL interface", tag))
         else
          `uvm_info("RX_TL_Monitor", $sformatf("[%s] Successfully accessed interface", tag), UVM_HIGH)
      end

      default: `uvm_fatal("TX_TL_Monitor", $sformatf("[%s] Unknown mode", tag))

    endcase

  endfunction

  task run_phase(uvm_phase phase);
    super.run_phase(phase);

    case(cfg.mode)

      RC_MODE: begin
        TX_TL_DL.tl_rx_ready = 1;
    `uvm_info("RX_TL_MONITOR", $sformatf("RC MODE TL MONITOR"), UVM_HIGH)
        fork
          // Thread 1 - forever collect TX requests (RC sending to EP)
	 begin
          forever begin
            Sequence_item t_x;
            t_x = Sequence_item::type_id::create("t_x");
            rc_sending_tx_request(t_x);
          end
         end
          // Thread 2 - forever collect RX completions (EP sending back to RC)
         begin 
	  forever begin
            Sequence_item r_x;
            r_x = Sequence_item::type_id::create("r_x");
            rc_collecting_rx_completion(r_x);
          end
	 end
        join_none
      end

      EP_MODE: begin
        RX_TL_DL.tl_rx_ready = 1;
    `uvm_info("RX_TL_MONITOR", $sformatf("EP MODE TL MONITOR"), UVM_HIGH)
        fork
          // Thread 1 - forever collect RX requests arriving at EP
          forever begin
            Sequence_item r_x;
            r_x = Sequence_item::type_id::create("r_x");
            ep_collecting_tx_request(r_x);
          end

          // Thread 2 - forever collect TX completions generated by EP LUT
          forever begin
            Sequence_item t_x;
            t_x = Sequence_item::type_id::create("t_x");
            ep_sending_rx_completion(t_x);
          end
        join_none
      end

      default: `uvm_fatal("TX_TL_Monitor", $sformatf("[%s] Unknown mode", tag))

    endcase

  endtask : run_phase


  //=============================================================
  // RC_MODE tasks - preserved exactly as TX_TL_Monitor.sv
  //=============================================================

  task rc_sending_tx_request(Sequence_item t_x);

    bit [31:0] dw;
    int header_dw;
    int payload_length;
      @(negedge TX_TL_DL.CLK);
    wait(TX_TL_DL.tl_tx_valid);
    ////////////////////////////// HEADER DW0 //////////////////////////////
    `uvm_info("RC_TL_MONITOR", $sformatf("RC MODE TL MONITOR inside TX_request"), UVM_HIGH)
      do begin
        @(negedge TX_TL_DL.CLK);
      end while(!(TX_TL_DL.tl_tx_valid && TX_TL_DL.tl_tx_ready));

    `uvm_info("RC_TL_MONITOR", $sformatf("RC MODE TL MONITOR DATA COLLECT"), UVM_HIGH)
    dw = TX_TL_DL.tl_tx_data;

    t_x.tlp_q.delete();
    t_x.tlp_q.push_back(dw);

    t_x.fmt    = dw[31:29];
    t_x.r_type = dw[28:24];
    t_x.length = dw[9:0];
    t_x.td     = dw[15];

    // header DW count
    case(t_x.fmt)
      3'b000, 3'b010 : header_dw = 3;
      3'b001, 3'b011 : header_dw = 4;
      default         : header_dw = 3;
    endcase

    ////////////////////////////// REMAINING HEADER //////////////////////////////
    for(int i = 1; i < header_dw; i++) begin
      do begin
        @(negedge TX_TL_DL.CLK);
      end while(!(TX_TL_DL.tl_tx_valid && TX_TL_DL.tl_tx_ready));
      dw = TX_TL_DL.tl_tx_data;
      t_x.tlp_q.push_back(dw);
    end
    foreach(t_x.tlp_q[i])
    `uvm_info("RC_TL_MONITOR", $sformatf("HEADER %h header_dw = %d",t_x.tlp_q[i],header_dw), UVM_HIGH)

    if(header_dw >= 3) begin
      t_x.addr = t_x.tlp_q[2];
    end

    ////////////////////////////// PAYLOAD //////////////////////////////
    payload_length = t_x.length;

    if(t_x.fmt inside {3'b010, 3'b011}) begin
      t_x.payload = new[payload_length];
      for(int i = 0; i < payload_length; i++) begin
        do begin
          @(negedge TX_TL_DL.CLK);
        end while(!(TX_TL_DL.tl_tx_valid && TX_TL_DL.tl_tx_ready));
        dw = TX_TL_DL.tl_tx_data;
        t_x.payload[i] = dw;
        t_x.tlp_q.push_back(dw);
      end
    end

    ////////////////////////////// ECRC //////////////////////////////
    if(t_x.td) begin
      do begin
        @(negedge TX_TL_DL.CLK);
      end while(!(TX_TL_DL.tl_tx_valid && TX_TL_DL.tl_tx_ready));
      dw = TX_TL_DL.tl_tx_data;
      t_x.ECRC = dw;
      t_x.tlp_q.push_back(dw);
    end
    foreach(t_x.tlp_q[i])
    `uvm_info("RC_TL_MONITOR", $sformatf("HEADER data %h header_dw = %d",t_x.tlp_q[i],header_dw), UVM_HIGH)

    `uvm_info("TX_TL_MONITOR", "=======================================================", UVM_HIGH)
    foreach(t_x.tlp_q[i])
      `uvm_info("TX_TL_MONITOR", $sformatf("[%s] TL_TX_MONITOR_TLP_PACKET[%0d] = %0h @(%0t)", tag, i, t_x.tlp_q[i], $time), UVM_HIGH)

    `uvm_info("TX_TL_MONITOR", $sformatf("[%s] DEBUG TX MONITOR - fmt=%0b r_type=%0b addr=%0h length=%0d",
                                          tag, t_x.fmt, t_x.r_type, t_x.addr, t_x.length), UVM_HIGH)

    `uvm_info("TX_TL_MONITOR",
      $sformatf("[%s] TX request collected and sent to scoreboard: fmt=%0b r_type=%0b addr=%0h length=%0d",
        tag, t_x.fmt, t_x.r_type, t_x.addr, t_x.length), UVM_LOW)

    TX_TL_Send.write(t_x);

  endtask : rc_sending_tx_request


  task rc_collecting_rx_completion(Sequence_item r_x);

    bit [31:0] dw;
    int header_dw;
    int payload_dw;
    bit [31:0] calculated_ecrc;

    ////////////////////////////// HEADER DW0 //////////////////////////////
    do begin
      @(posedge TX_TL_DL.CLK);
    end while(!(TX_TL_DL.tl_rx_valid && TX_TL_DL.tl_rx_ready));

    dw = TX_TL_DL.tl_rx_data;

    r_x.tlp_q.delete();
    r_x.tlp_q.push_back(dw);

    r_x.fmt    = dw[31:29];
    r_x.r_type = dw[28:24];
    r_x.length = dw[9:0];
    r_x.td     = dw[15];

    // header DW count
    case(r_x.fmt)
      3'b000, 3'b010 : header_dw = 3;
      3'b001, 3'b011 : header_dw = 4;
      default         : header_dw = 3;
    endcase

    ////////////////////////////// REMAINING HEADER //////////////////////////////
    for(int i = 1; i < header_dw; i++) begin
      do begin
        @(posedge TX_TL_DL.CLK);
      end while(!(TX_TL_DL.tl_rx_valid && TX_TL_DL.tl_rx_ready));
      dw = TX_TL_DL.tl_rx_data;
      r_x.tlp_q.push_back(dw);
    end

    r_x.req_id = r_x.tlp_q[2][31:16];
    r_x.tag    = r_x.tlp_q[2][15:8];

    `uvm_info("TX_TL_MONITOR", $sformatf("[%s] REQ_ID = %0d TAG = %0d", tag, r_x.req_id, r_x.tag), UVM_HIGH)

    if(header_dw >= 3) begin
      r_x.addr = r_x.tlp_q[3];
    end

    ////////////////////////////// PAYLOAD //////////////////////////////
    payload_dw = r_x.length;

    if(r_x.fmt inside {3'b010, 3'b011}) begin
      r_x.payload = new[payload_dw];
      for(int i = 0; i < payload_dw; i++) begin
        do begin
          @(posedge TX_TL_DL.CLK);
        end while(!(TX_TL_DL.tl_rx_valid && TX_TL_DL.tl_rx_ready));
        dw = TX_TL_DL.tl_rx_data;
        r_x.payload[i] = dw;
        r_x.tlp_q.push_back(dw);
      end
    end

    ////////////////////////////// ECRC CHECK //////////////////////////////
    if(r_x.td) begin
      do begin
        @(posedge TX_TL_DL.CLK);
      end while(!(TX_TL_DL.tl_rx_valid && TX_TL_DL.tl_rx_ready));
      dw = TX_TL_DL.tl_rx_data;
      r_x.ECRC = dw;

      calculated_ecrc = r_x.calculate_ecrc();

      `uvm_info("TX_TL_MONITOR", $sformatf("[%s] RX ECRC CHECK: RECEIVED=%08h CALCULATED=%08h", tag, r_x.ECRC, calculated_ecrc), UVM_HIGH)

      if(calculated_ecrc == r_x.ECRC) begin
        r_x.ecrc_error   = 1'b0;
        r_x.compl_status = 3'b000;
        r_x.tlp_q.push_back(r_x.ECRC);

        foreach(r_x.tlp_q[i])
          `uvm_info("TX_TL_MONITOR", $sformatf("[%s] TX_TLP[%0d] = %08h @ %0t", tag, i, r_x.tlp_q[i], $time), UVM_HIGH)

        `uvm_info("TX_TL_MONITOR",
          $sformatf("[%s] RX completion collected (ECRC OK) and sent to scoreboard: length=%0d",
            tag, r_x.length), UVM_LOW)

        TX_TL_Send.write(r_x);

      end else begin
        r_x.ecrc_error = 1'b1;
        `uvm_error("TX_TL_MONITOR", $sformatf("[%s] ECRC MISMATCH - PACKET DROPPED", tag))
      end

    end else begin
      r_x.ecrc_error   = 1'b0;
      r_x.compl_status = 3'b000;

      foreach(r_x.tlp_q[i])
        `uvm_info("TX_TL_MONITOR", $sformatf("[%s] TX_TLP[%0d] = %08h @ %0t", tag, i, r_x.tlp_q[i], $time), UVM_HIGH)

      `uvm_info("TX_TL_MONITOR",
        $sformatf("[%s] RX completion collected (no ECRC) and sent to scoreboard: length=%0d",
          tag, r_x.length), UVM_LOW)

      TX_TL_Send.write(r_x);

    end

    wait(TX_TL_DL.tl_rx_valid == 0);

  endtask : rc_collecting_rx_completion


  //=============================================================
  // EP_MODE tasks - preserved exactly as RX_TL_Monitor.sv
  //=============================================================

  task ep_collecting_tx_request(Sequence_item r_x);

    bit [31:0] dw;
    int header_dw;
    int payload_dw;
    bit [31:0] calculated_ecrc;

    ////////////////////////////// HEADER DW0 //////////////////////////////
    do begin
      @(posedge RX_TL_DL.CLK);
    end while(!(RX_TL_DL.tl_rx_valid && RX_TL_DL.tl_rx_ready));

    dw = RX_TL_DL.tl_rx_data;

    r_x.tlp_q.delete();
    r_x.tlp_q.push_back(dw);

    r_x.fmt    = dw[31:29];
    r_x.r_type = dw[28:24];
    r_x.length = dw[9:0];
    r_x.td     = dw[15];
    r_x.at     = dw[11:10];

    // header DW count
    case(r_x.fmt)
      3'b000, 3'b010 : header_dw = 3;
      3'b001, 3'b011 : header_dw = 4;
      default        : header_dw = 3;
    endcase

    ////////////////////////////// REMAINING HEADER //////////////////////////////
    for(int i = 1; i < header_dw; i++) begin
      do begin
        @(posedge RX_TL_DL.CLK);
      end while(!(RX_TL_DL.tl_rx_valid && RX_TL_DL.tl_rx_ready));
      dw = RX_TL_DL.tl_rx_data;
      r_x.tlp_q.push_back(dw);
    end

    r_x.req_id           = r_x.tlp_q[1][31:16];
    r_x.tag              = r_x.tlp_q[1][15:8];
    r_x.last_BE          = r_x.tlp_q[1][7:4];
    r_x.first_BE         = r_x.tlp_q[1][3:0];
    r_x.ep_bus           = r_x.tlp_q[2][31:24];
    r_x.ep_device        = r_x.tlp_q[2][23:19];
    r_x.ep_function_n    = r_x.tlp_q[2][18:16];
    r_x.ext_register_num = r_x.tlp_q[2][11:8];
    r_x.register_num     = r_x.tlp_q[2][7:2];
    r_x.R4               = r_x.tlp_q[2][1:0];

    `uvm_info("RX_TL_MONITOR", $sformatf("[%s] BYTE_COUNT = %0d REQ_ID = %0d TAG = %0d EP_DEVICE = %0h", tag, r_x.byte_count, r_x.req_id, r_x.tag, r_x.ep_device), UVM_HIGH)
    `uvm_info("MON",
$sformatf("MON: reg_num=%0d ext_reg=%0d",
r_x.register_num, r_x.ext_register_num), UVM_HIGH)

    if(header_dw >= 3) begin
      r_x.addr = r_x.tlp_q[2];
    end

    ////////////////////////////// PAYLOAD //////////////////////////////
    payload_dw = r_x.length;

    if(r_x.fmt inside {3'b010, 3'b011}) begin
      r_x.payload = new[payload_dw];
      for(int i = 0; i < payload_dw; i++) begin
        do begin
          @(posedge RX_TL_DL.CLK);
        end while(!(RX_TL_DL.tl_rx_valid && RX_TL_DL.tl_rx_ready));
        dw = RX_TL_DL.tl_rx_data;
        r_x.payload[i] = dw;
        r_x.tlp_q.push_back(dw);
      end
    end

    ////////////////////////////// ECRC CHECK //////////////////////////////
    if(r_x.td) begin
      do begin
        @(posedge RX_TL_DL.CLK);
      end while(!(RX_TL_DL.tl_rx_valid && RX_TL_DL.tl_rx_ready));
      dw = RX_TL_DL.tl_rx_data;
      r_x.ECRC = dw;

      calculated_ecrc = r_x.calculate_ecrc();

      `uvm_info("RX_TL_MONITOR", $sformatf("[%s] RX ECRC CHECK: RECEIVED=%08h CALCULATED=%08h", tag, r_x.ECRC, calculated_ecrc), UVM_HIGH)

      if(calculated_ecrc == r_x.ECRC) begin
        r_x.ecrc_error   = 1'b0;
        r_x.compl_status = 3'b000;
        r_x.tlp_q.push_back(r_x.ECRC);

        foreach(r_x.tlp_q[i])
          `uvm_info("RX_TL_MONITOR", $sformatf("[%s] RX_TLP[%0d] = %08h @ %0t", tag, i, r_x.tlp_q[i], $time), UVM_HIGH)

        `uvm_info("RX_TL_MONITOR",
          $sformatf("[%s] RX request collected (ECRC OK) and sent to scoreboard: addr=%0h length=%0d tag=%0d",
            tag, r_x.addr, r_x.length, r_x.tag), UVM_LOW)
        RX_TL_Send.write(r_x);

	`uvm_info("MON_TO_LUT",
$sformatf("Sending to LUT: reg=%0d tag=%0d",
          r_x.register_num,
          r_x.tag),
UVM_LOW)
        RX_TL_MON_Send.write(r_x);

      end else begin
        r_x.ecrc_error = 1'b1;
        `uvm_error("RX_TL_MONITOR", $sformatf("[%s] ECRC MISMATCH - PACKET DROPPED", tag))
      end

    end else begin
      r_x.ecrc_error   = 1'b0;
      r_x.compl_status = 3'b000;

      foreach(r_x.tlp_q[i])
        `uvm_info("RX_TL_MONITOR", $sformatf("[%s] RX_TLP[%0d] = %08h @ %0t", tag, i, r_x.tlp_q[i], $time), UVM_HIGH)

      `uvm_info("RX_TL_MONITOR",
        $sformatf("[%s] RX request collected (no ECRC) and sent to scoreboard/LUT: addr=%0h length=%0d tag=%0d",
          tag, r_x.addr, r_x.length, r_x.tag), UVM_LOW)
      RX_TL_Send.write(r_x);
      RX_TL_MON_Send.write(r_x);
          end

    wait(RX_TL_DL.tl_rx_valid == 0);

  endtask : ep_collecting_tx_request


  task ep_sending_rx_completion(Sequence_item t_x);

    bit [31:0] dw;
    int header_dw;
    int payload_length;

    ////////////////////////////// HEADER DW0 //////////////////////////////
    do begin
      @(posedge RX_TL_DL.CLK);
    end while(!(RX_TL_DL.tl_tx_valid && RX_TL_DL.tl_tx_ready));

    dw = RX_TL_DL.tl_tx_data;

    t_x.tlp_q.delete();
    t_x.tlp_q.push_back(dw);

    t_x.fmt    = dw[31:29];
    t_x.r_type = dw[28:24];
    t_x.length = dw[9:0];
    t_x.td     = dw[15];

    // header DW count
    case(t_x.fmt)
      3'b000, 3'b010 : header_dw = 3;
      3'b001, 3'b011 : header_dw = 4;
      default         : header_dw = 3;
    endcase

    ////////////////////////////// REMAINING HEADER //////////////////////////////
    for(int i = 1; i < header_dw; i++) begin
      do begin
        @(posedge RX_TL_DL.CLK);
      end while(!(RX_TL_DL.tl_tx_valid && RX_TL_DL.tl_tx_ready));
      dw = RX_TL_DL.tl_tx_data;
      t_x.tlp_q.push_back(dw);
    end

    ////////////////////////////// PAYLOAD //////////////////////////////
    payload_length = t_x.length;

    if(t_x.fmt inside {3'b010, 3'b011}) begin
      t_x.payload = new[payload_length];
      for(int i = 0; i < payload_length; i++) begin
        do begin
          @(posedge RX_TL_DL.CLK);
        end while(!(RX_TL_DL.tl_tx_valid && RX_TL_DL.tl_tx_ready));
        dw = RX_TL_DL.tl_tx_data;
        t_x.payload[i] = dw;
        t_x.tlp_q.push_back(dw);
      end
    end

    ////////////////////////////// ECRC //////////////////////////////
    if(t_x.td) begin
      do begin
        @(posedge RX_TL_DL.CLK);
      end while(!(RX_TL_DL.tl_tx_valid && RX_TL_DL.tl_tx_ready));
      dw = RX_TL_DL.tl_tx_data;
      t_x.ECRC = dw;
      t_x.tlp_q.push_back(dw);
    end

    foreach(t_x.tlp_q[i])
      `uvm_info("RX_TL_MONITOR", $sformatf("[%s] TL_RX_MONITOR_TLP_PACKET[%0d] = %0h @(%0t)", tag, i, t_x.tlp_q[i], $time), UVM_HIGH)

    `uvm_info("RX_TL_MONITOR",
      $sformatf("[%s] EP completion collected and sent to scoreboard: fmt=%0b r_type=%0b length=%0d",
        tag, t_x.fmt, t_x.r_type, t_x.length), UVM_LOW)

    RX_TL_Send.write(t_x);

    wait(RX_TL_DL.tl_tx_valid == 0);

  endtask : ep_sending_rx_completion

endclass : PCIe_TL_Monitor

