//-----------------------------------------------------------------
// TX_TL_Monitor
//   Lives under one Env_Top instance, gets its own env_cfg, and
//   runs the REAL TL-layer monitor logic for whichever role
//   cfg.mode says it is - two concurrent threads per role.
//
//   RC_MODE (real TX_TL_Monitor.sv reference): thread 1 captures
//   outgoing TX requests off TX_TL_DL, thread 2 captures incoming
//   RX completions (with ECRC check) off TX_TL_DL, both published
//   on TX_TL_Send.
//
//   EP_MODE (real RX_TL_Monitor.sv reference): thread 1 captures
//   incoming TX requests off RX_TL_DL (with ECRC check) - this is
//   what feeds RX_PCIe_LUT via RX_TL_MON_Send (wired in Env_Top's
//   connect_phase). Thread 2 captures outgoing completion TLPs
//   generated by the LUT/driver off RX_TL_DL, published on
//   RX_TL_Send.
//
//   The reference project's e_type (tlp_type_e) field was used
//   only for $display debug logging here, never for control flow
//   - per the same fmt/r_type-only design decision used for
//   RX_PCIe_LUT, those debug lines print raw fmt/r_type values
//   instead of decoding to an e_type name.
//-----------------------------------------------------------------
class PCIe_TL_Monitor extends uvm_monitor;

  `uvm_component_utils(PCIe_TL_Monitor)

  env_cfg cfg;
  string  tag;

  //-----------------------------------------------------------
  //  Static Sequence item queue to collect the packets from TL
  //  TX Monitor
  //-----------------------------------------------------------
  
  static Sequence_item cpl_q[$];
  
  //-----------------------------------------------------------
  // Role-specific interface handles
  //-----------------------------------------------------------
  virtual TX_TL_DL_Interface TX_TL_DL;   // RC_MODE
  virtual RX_TL_DL_Interface RX_TL_DL;   // EP_MODE

  //-----------------------------------------------------------
  // RC_MODE analysis port
  //-----------------------------------------------------------
  uvm_analysis_port #(Sequence_item) TX_TL_Send;

  //-----------------------------------------------------------
  // EP_MODE analysis ports
  //   RX_TL_MON_Send specifically feeds RX_PCIe_LUT (wired in
  //   Env_Top's connect_phase to PCIe_LUT.RX_LUT_imp).
  //-----------------------------------------------------------
  uvm_analysis_port #(Sequence_item) RX_TL_Send;
  uvm_analysis_port #(Sequence_item) RX_TL_MON_Send;

  function new(string name = "PCIe_TL_Monitor", uvm_component parent = null);
    super.new(name, parent);
    TX_TL_Send     = new("TX_TL_Send", this);
    RX_TL_Send     = new("RX_TL_Send", this);
    RX_TL_MON_Send = new("RX_TL_MON_Send", this);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);

    if(!uvm_config_db#(env_cfg)::get(this, "", "env_cfg", cfg))
      `uvm_fatal("TX_TL_Monitor", $sformatf("env_cfg not found for %s", get_full_name()))

    tag = get_full_name();
    `uvm_info("TX_TL_Monitor", $sformatf("[%s] Configured: mode=%s", tag, cfg.mode.name()), UVM_LOW)

    case(cfg.mode)

      RC_MODE: begin
        if(!uvm_config_db#(virtual TX_TL_DL_Interface)::get(this, "", "TL_Vif", TX_TL_DL))
          `uvm_fatal("TX_TL_Monitor", $sformatf("[%s] Unable to access TX_TL_DL interface", tag))
        else
          `uvm_info("TX_TL_Monitor", $sformatf("[%s] Successfully accessed interface", tag), UVM_LOW)
      end

      EP_MODE: begin
        if(!uvm_config_db#(virtual RX_TL_DL_Interface)::get(this, "", "TL_Vif", RX_TL_DL))
          `uvm_fatal("RX_TL_MONITOR", $sformatf("[%s] Unable to access RX TL interface", tag))
         else
          `uvm_info("RX_TL_Monitor", $sformatf("[%s] Successfully accessed interface", tag), UVM_LOW)
      end

      default: `uvm_fatal("TX_TL_Monitor", $sformatf("[%s] Unknown mode", tag))

    endcase

  endfunction

  task run_phase(uvm_phase phase);
    super.run_phase(phase);

    case(cfg.mode)

      RC_MODE: begin
        TX_TL_DL.tl_rx_ready = 1;
    `uvm_info("RX_TL_MONITOR", $sformatf("RC MODE TL MONITOR"), UVM_LOW)
        fork
          // Thread 1 - forever collect TX requests (RC sending to EP)
	 begin
          forever begin
            Sequence_item t_x;
            t_x = Sequence_item::type_id::create("t_x");
            rc_sending_tx_request(t_x);
          end
         end
          // Thread 2 - forever collect RX completions (EP sending back to RC)
         begin 
	  forever begin
            Sequence_item r_x;
            r_x = Sequence_item::type_id::create("r_x");
            rc_collecting_rx_completion(r_x);
          end
	 end
        join_none
      end

      EP_MODE: begin
        RX_TL_DL.tl_rx_ready = 1;
    `uvm_info("RX_TL_MONITOR", $sformatf("EP MODE TL MONITOR"), UVM_LOW)
        fork
          // Thread 1 - forever collect RX requests arriving at EP
          forever begin
            Sequence_item r_x;
            r_x = Sequence_item::type_id::create("r_x");
            ep_collecting_tx_request(r_x);
          end

          // Thread 2 - forever collect TX completions generated by EP LUT
          forever begin
            Sequence_item t_x;
            t_x = Sequence_item::type_id::create("t_x");
            ep_sending_rx_completion(t_x);
          end
        join_none
      end

      default: `uvm_fatal("TX_TL_Monitor", $sformatf("[%s] Unknown mode", tag))

    endcase

  endtask : run_phase


  //=============================================================
  // RC_MODE tasks - preserved exactly as TX_TL_Monitor.sv
  //=============================================================

  task rc_sending_tx_request(Sequence_item t_x);

    bit [31:0] dw;
    int header_dw;
    int payload_length;
      @(negedge TX_TL_DL.CLK);
    wait(TX_TL_DL.tl_tx_valid);
    ////////////////////////////// HEADER DW0 //////////////////////////////
    `uvm_info("RC_TL_MONITOR", $sformatf("RC MODE TL MONITOR inside TX_request"), UVM_LOW)
      do begin
        @(negedge TX_TL_DL.CLK);
      end while(!(TX_TL_DL.tl_tx_valid && TX_TL_DL.tl_tx_ready));

    `uvm_info("RC_TL_MONITOR", $sformatf("RC MODE TL MONITOR DATA COLLECT"), UVM_LOW)
    dw = TX_TL_DL.tl_tx_data;

    t_x.tlp_q.delete();
    t_x.tlp_q.push_back(dw);

    t_x.fmt    = dw[31:29];
    t_x.r_type = dw[28:24];
    t_x.length = dw[9:0];
    t_x.td     = dw[15];
     case(t_x.r_type)
      5'b00000 :
        if(t_x.fmt inside {3'b000, 3'b001})
          t_x.e_type = MEM_RD;
        else
          t_x.e_type = MEM_WR;

      5'b00010 :
        if(t_x.fmt == 3'b000)
          t_x.e_type = IO_RD;
        else
          t_x.e_type = IO_WR;

      5'b00100 :
        if(t_x.fmt == 3'b000)
          t_x.e_type = CFG_RD0;
        else
          t_x.e_type = CFG_WR0;

      5'b00101 :
        if(t_x.fmt == 3'b000)
          t_x.e_type = CFG_RD1;
        else
          t_x.e_type = CFG_WR1;

      5'b01010 :
        if(t_x.fmt==3'b000)
          t_x.e_type = CPL;
        else if(t_x.fmt==3'b010)
          t_x.e_type = CPL_DATA;

    endcase




    // header DW count
    case(t_x.fmt)
      3'b000, 3'b010 : header_dw = 3;
      3'b001, 3'b011 : header_dw = 4;
      default         : header_dw = 3;
    endcase

    ////////////////////////////// REMAINING HEADER //////////////////////////////
    for(int i = 1; i < header_dw; i++) begin
      do begin
        @(negedge TX_TL_DL.CLK);
      end while(!(TX_TL_DL.tl_tx_valid && TX_TL_DL.tl_tx_ready));
      dw = TX_TL_DL.tl_tx_data;
      t_x.tlp_q.push_back(dw);
    end
    foreach(t_x.tlp_q[i])
    `uvm_info("RC_TL_MONITOR", $sformatf("HEADER %h header_dw = %d",t_x.tlp_q[i],header_dw), UVM_LOW)

  
// ADD THESE LINES:
    t_x.req_id   = t_x.tlp_q[1][31:16];
    t_x.tag      = t_x.tlp_q[1][15:8];
    t_x.last_BE  = t_x.tlp_q[1][7:4];
    t_x.first_BE = t_x.tlp_q[1][3:0];

   if(header_dw == 3) begin
  t_x.addr = t_x.tlp_q[2];
end
else if(header_dw == 4) begin
  t_x.addr = {t_x.tlp_q[2], t_x.tlp_q[3][31:2], 2'b00};
end
        ////////////////////////////// PAYLOAD //////////////////////////////
    payload_length = t_x.length;

    if(t_x.fmt inside {3'b010, 3'b011}) begin
      t_x.payload = new[payload_length];
      for(int i = 0; i < payload_length; i++) begin
        do begin
          @(negedge TX_TL_DL.CLK);
        end while(!(TX_TL_DL.tl_tx_valid && TX_TL_DL.tl_tx_ready));
        dw = TX_TL_DL.tl_tx_data;
        t_x.payload[i] = dw;
        t_x.tlp_q.push_back(dw);
      end
    end

    ////////////////////////////// ECRC //////////////////////////////
    if(t_x.td) begin
      do begin
        @(negedge TX_TL_DL.CLK);
      end while(!(TX_TL_DL.tl_tx_valid && TX_TL_DL.tl_tx_ready));
      dw = TX_TL_DL.tl_tx_data;
      t_x.ECRC = dw;
      t_x.tlp_q.push_back(dw);
    end
    foreach(t_x.tlp_q[i])
    `uvm_info("RC_TL_MONITOR", $sformatf("HEADER data %h header_dw = %d",t_x.tlp_q[i],header_dw), UVM_LOW)

    `uvm_info("TX_TL_MONITOR", "=======================================================", UVM_LOW)
    foreach(t_x.tlp_q[i])
      `uvm_info("TX_TL_MONITOR", $sformatf("[%s] TL_TX_MONITOR_TLP_PACKET[%0d] = %0h @(%0t)", tag, i, t_x.tlp_q[i], $time), UVM_LOW)

    `uvm_info("TX_TL_MONITOR", $sformatf("[%s] DEBUG TX MONITOR - fmt=%0b r_type=%0b addr=%0h length=%0d",
                                          tag, t_x.fmt, t_x.r_type, t_x.addr, t_x.length), UVM_LOW)

    TX_TL_Send.write(t_x);

  endtask : rc_sending_tx_request


  task rc_collecting_rx_completion(Sequence_item r_x);

    bit [31:0] dw;
    int header_dw;
    int payload_dw;
    bit [31:0] calculated_ecrc;

    ////////////////////////////// HEADER DW0 //////////////////////////////
    do begin
      @(posedge TX_TL_DL.CLK);
    end while(!(TX_TL_DL.tl_rx_valid && TX_TL_DL.tl_rx_ready));

    dw = TX_TL_DL.tl_rx_data;

    r_x.tlp_q.delete();
    r_x.tlp_q.push_back(dw);

    r_x.fmt    = dw[31:29];
    r_x.r_type = dw[28:24];
    r_x.length = dw[9:0];
    r_x.td     = dw[15];
     case(r_x.r_type)
      5'b00000 :
        if(r_x.fmt inside {3'b000, 3'b001})
          r_x.e_type = MEM_RD;
        else
          r_x.e_type = MEM_WR;

      5'b00010 :
        if(r_x.fmt == 3'b000)
          r_x.e_type = IO_RD;
        else
          r_x.e_type = IO_WR;

      5'b00100 :
        if(r_x.fmt == 3'b000)
          r_x.e_type = CFG_RD0;
        else
          r_x.e_type = CFG_WR0;

      5'b00101 :
        if(r_x.fmt == 3'b000)
          r_x.e_type = CFG_RD1;
        else
          r_x.e_type = CFG_WR1;

      5'b01010 :
        if(r_x.fmt ==3'b000)
          r_x.e_type = CPL;
        else if (r_x.fmt==3'b010)
          r_x.e_type = CPL_DATA;

    endcase



    // header DW count
    case(r_x.fmt)
      3'b000, 3'b010 : header_dw = 3;
      3'b001, 3'b011 : header_dw = 4;
      default         : header_dw = 3;
    endcase

    ////////////////////////////// REMAINING HEADER //////////////////////////////
    for(int i = 1; i < header_dw; i++) begin
      do begin
        @(posedge TX_TL_DL.CLK);
      end while(!(TX_TL_DL.tl_rx_valid && TX_TL_DL.tl_rx_ready));
      dw = TX_TL_DL.tl_rx_data;
      r_x.tlp_q.push_back(dw);
    end

    r_x.req_id = r_x.tlp_q[2][31:16];
    r_x.tag    = r_x.tlp_q[2][15:8];

     r_x.lower_addr   = r_x.tlp_q[2][6:0];
    r_x.completer_id = r_x.tlp_q[1][31:16];
    r_x.compl_status = r_x.tlp_q[1][15:13];
    r_x.bcm          = r_x.tlp_q[1][12];
    r_x.byte_count   = r_x.tlp_q[1][11:0];

    `uvm_info("TX_TL_MONITOR", $sformatf("[%s] REQ_ID = %0d TAG = %0d BYTE_COUNT=%0d", tag, r_x.req_id, r_x.tag, r_x.byte_count), UVM_HIGH)

 //   if(header_dw >= 3) begin
   //   r_x.addr = r_x.tlp_q[3];
//    end

    ////////////////////////////// PAYLOAD //////////////////////////////
    payload_dw = r_x.length;

    if(r_x.fmt inside {3'b010, 3'b011}) begin
      r_x.payload = new[payload_dw];
      for(int i = 0; i < payload_dw; i++) begin
        do begin
          @(posedge TX_TL_DL.CLK);
        end while(!(TX_TL_DL.tl_rx_valid && TX_TL_DL.tl_rx_ready));
        dw = TX_TL_DL.tl_rx_data;
        r_x.payload[i] = dw;
        r_x.tlp_q.push_back(dw);
      end
    end

    ////////////////////////////// ECRC CHECK //////////////////////////////
    if(r_x.td) begin
      do begin
        @(posedge TX_TL_DL.CLK);
      end while(!(TX_TL_DL.tl_rx_valid && TX_TL_DL.tl_rx_ready));
      dw = TX_TL_DL.tl_rx_data;
      r_x.ECRC = dw;

      calculated_ecrc = r_x.calculate_ecrc();

      `uvm_info("TX_TL_MONITOR", $sformatf("[%s] RX ECRC CHECK: RECEIVED=%08h CALCULATED=%08h", tag, r_x.ECRC, calculated_ecrc), UVM_LOW)

      if(calculated_ecrc == r_x.ECRC) begin
        r_x.ecrc_error   = 1'b0;
        r_x.tlp_q.push_back(r_x.ECRC);

        foreach(r_x.tlp_q[i])
          `uvm_info("TX_TL_MONITOR", $sformatf("[%s] TX_TLP[%0d] = %08h @ %0t", tag, i, r_x.tlp_q[i], $time), UVM_LOW)

        // FIX: compl_status==UR is a legal, expected completion
        // (that's the point of the UR test) - it must still be
        // forwarded on TX_TL_Send so the scoreboard/subscribers
        // actually see it, not dropped like a corrupted packet.
        if(r_x.compl_status == 3'b001)
          `uvm_error("TX_TL_MONITOR", $sformatf("[%s] UNSUPPORTED_REQ completion received (UR)", tag))
        if(r_x.compl_status == 3'b100)
          `uvm_error("TX_TL_MONITOR", $sformatf("[%s] COMPLETER_ABORT completion received (CA)", tag))
        TX_TL_Send.write(r_x);

      end else begin
        r_x.ecrc_error = 1'b1;
        `uvm_error("TX_TL_MONITOR", $sformatf("[%s] ECRC MISMATCH - PACKET DROPPED", tag))
      end

    end else begin
      r_x.ecrc_error   = 1'b0;
      // FIX: this used to force compl_status back to 3'b000 here,
      // clobbering the real status already parsed from the header
      // (r_x.compl_status = r_x.tlp_q[1][15:13] above). That hid a
      // UR completion whenever it arrived without an ECRC (td==0).
      // compl_status is independent of whether ECRC is present, so
      // just leave the parsed value alone.

      foreach(r_x.tlp_q[i])
        `uvm_info("TX_TL_MONITOR", $sformatf("[%s] TX_TLP[%0d] = %08h @ %0t", tag, i, r_x.tlp_q[i], $time), UVM_LOW)


      //--------------------------------------------------------------------------
      // Write method called to send to TL Scoreboard 
      //--------------------------------------------------------------------------

        // FIX: same as above - forward UR completions too instead
        // of dropping them.
        if(r_x.compl_status == 3'b001)
          `uvm_error("TX_TL_MONITOR", $sformatf("[%s] UNSUPPORTED_REQ completion received (UR)", tag))
        if(r_x.compl_status == 3'b100)
          `uvm_error("TX_TL_MONITOR", $sformatf("[%s] COMPLETER_ABORT completion received (CA)", tag))
        TX_TL_Send.write(r_x);

      `uvm_info("TL_MON", "Writing completion to analysis port", UVM_LOW)

    end

    //------------------------------------------------------------------
    // Pushing into the Sequence item static queue to check in test 
    //------------------------------------------------------------------ 

    if (!r_x.ecrc_error && r_x.r_type == 5'b01010) begin

      Sequence_item cpl;

      cpl = Sequence_item::type_id::create("cpl");
      cpl.copy(r_x);

      //$cast(cpl, r_x.clone());
      
      cpl_q.delete();

      `uvm_info("TL_MONITOR", "Static Queue Is Deleted", UVM_LOW)
      
      cpl_q.push_back(cpl);

      `uvm_info("TX_MONITOR", $sformatf("Size = %0d", cpl_q.size), UVM_LOW)

      `uvm_info("TX_MON", $sformatf("Completion stored. Queue Size=%0d Tag=%0d", cpl_q.size(),cpl.tag), UVM_LOW)

    end

    wait(TX_TL_DL.tl_rx_valid == 0);

  endtask : rc_collecting_rx_completion


  //=============================================================
  // EP_MODE tasks - preserved exactly as RX_TL_Monitor.sv
  //=============================================================

  task ep_collecting_tx_request(Sequence_item r_x);

    bit [31:0] dw;
    int header_dw;
    int payload_dw;
    int actual_payload_dw;
    bit [31:0] calculated_ecrc;
    bit malformed_length;   // ERR_LENGTH checker result - gates downstream forwarding

    ////////////////////////////// HEADER DW0 //////////////////////////////
    do begin
      @(posedge RX_TL_DL.CLK);
    end while(!(RX_TL_DL.tl_rx_valid && RX_TL_DL.tl_rx_ready));

    dw = RX_TL_DL.tl_rx_data;

    r_x.tlp_q.delete();
    r_x.tlp_q.push_back(dw);

    r_x.fmt    = dw[31:29];
    r_x.r_type = dw[28:24];
    r_x.length = dw[9:0];
    r_x.td     = dw[15];
    r_x.ep     = dw[14];
    r_x.at     = dw[11:10];

    //-----------------------------------------------------------
    // ERR_FMT_RTYPE checker (part 1): fmt[2]==1 (3'b1xx) is a
    // reserved encoding for every basic request/completion Type in
    // this bench's fmt_e (only 000/001/010/011 - {3,4}DW x {no-,}
    // data - are ever legally produced). Catches the injection even
    // when r_type itself is still a normal, otherwise-legal value
    // (Sequence_item::post_randomize() deliberately leaves r_type
    // alone under ERR_FMT_RTYPE).
    //-----------------------------------------------------------
    if (r_x.fmt[2]) begin
      `uvm_error("MALFORMED_TLP",
        $sformatf("[%s] Reserved fmt encoding: fmt=%03b (bit2 set) r_type=%05b - Malformed TLP",
                   tag, r_x.fmt, r_x.r_type))
    end

   case(r_x.r_type)
      5'b00000 :
        if(r_x.fmt inside {3'b000, 3'b001})
          r_x.e_type = MEM_RD;
        else
          r_x.e_type = MEM_WR;

      5'b00010 :
        if(r_x.fmt == 3'b000)
          r_x.e_type = IO_RD;
        else
          r_x.e_type = IO_WR;

      5'b00100 :
        if(r_x.fmt == 3'b000)
          r_x.e_type = CFG_RD0;
        else
          r_x.e_type = CFG_WR0;

      5'b00101 :
        if(r_x.fmt == 3'b000)
          r_x.e_type = CFG_RD1;
        else
          r_x.e_type = CFG_WR1;

      5'b01010 :
        if(r_x.fmt == 3'b000)
          r_x.e_type = CPL;
        else if (r_x.fmt==3'b010)
          r_x.e_type = CPL_DATA;

      //-----------------------------------------------------
      // ERR_FMT_RTYPE checker (part 2): any r_type not covered
      // above (00001/00011/00110-01001/01011-11111) is a reserved/
      // illegal Type field per the PCIe TLP header - a Malformed
      // TLP. Real hardware would treat this as an uncorrectable
      // Malformed TLP error (Fatal by default severity).
      //-----------------------------------------------------
      default : begin
        `uvm_error("MALFORMED_TLP",
          $sformatf("[%s] Illegal/reserved fmt+r_type combination: fmt=%03b r_type=%05b - Malformed TLP",
                     tag, r_x.fmt, r_x.r_type))
      end

    endcase

    // ERR_IO_LEN / ERR_CFG_LEN checker: IO and Config reads/writes
    // are architecturally required to carry Length==1 (a single
    // DW). Anything else is Malformed.
    if (r_x.r_type inside {5'b00010, 5'b00100, 5'b00101} && r_x.length != 10'd1) begin
      `uvm_error("MALFORMED_TLP",
        $sformatf("[%s] IO/CFG request with Length=%0d (must be 1) - Malformed TLP",
                   tag, r_x.length))
    end

    // header DW count
    case(r_x.fmt)
      3'b000, 3'b010 : header_dw = 3;
      3'b001, 3'b011 : header_dw = 4;
      default        : header_dw = 3;
    endcase

    ////////////////////////////// REMAINING HEADER //////////////////////////////
    for(int i = 1; i < header_dw; i++) begin
      do begin
        @(posedge RX_TL_DL.CLK);
      end while(!(RX_TL_DL.tl_rx_valid && RX_TL_DL.tl_rx_ready));
      dw = RX_TL_DL.tl_rx_data;
      r_x.tlp_q.push_back(dw);
    end

    r_x.req_id           = r_x.tlp_q[1][31:16];
    r_x.tag              = r_x.tlp_q[1][15:8];
    r_x.last_BE          = r_x.tlp_q[1][7:4];
    r_x.first_BE         = r_x.tlp_q[1][3:0];
    r_x.ep_bus           = r_x.tlp_q[2][31:24];
    r_x.ep_device        = r_x.tlp_q[2][23:19];
    r_x.ep_function_n    = r_x.tlp_q[2][18:16];
    r_x.ext_register_num = r_x.tlp_q[2][11:8];
    r_x.register_num     = r_x.tlp_q[2][7:2];
    r_x.R4               = r_x.tlp_q[2][1:0];

    //-----------------------------------------------------------
    // ERR_BYTE_EN checker: first_BE/last_BE must each be one of
    // the legal contiguous (or all-zero, for Length==1 don't-care)
    // patterns. A non-contiguous pattern like 4'b0101 is Malformed.
    //-----------------------------------------------------------
    if (r_x.e_type inside {MEM_RD, MEM_WR, IO_RD, IO_WR, CFG_RD0, CFG_WR0, CFG_RD1, CFG_WR1}) begin
      bit first_be_ok, last_be_ok;
      first_be_ok = r_x.first_BE inside {4'b0000, 4'b0001, 4'b0011, 4'b0111, 4'b1111,
                                          4'b1000, 4'b1100, 4'b1110};
      last_be_ok  = r_x.last_BE  inside {4'b0000, 4'b0001, 4'b0011, 4'b0111, 4'b1111,
                                          4'b1000, 4'b1100, 4'b1110};
      if (!first_be_ok || !last_be_ok) begin
        `uvm_error("MALFORMED_TLP",
          $sformatf("[%s] Illegal byte-enable pattern: first_BE=%04b last_BE=%04b - Malformed TLP",
                     tag, r_x.first_BE, r_x.last_BE))
      end
    end



    `uvm_info("RX_TL_MONITOR", $sformatf("[%s] BYTE_COUNT = %0d REQ_ID = %0d TAG = %0d EP_DEVICE = %0h", tag, r_x.byte_count, r_x.req_id, r_x.tag, r_x.ep_device), UVM_LOW)
    `uvm_info("MON",
$sformatf("MON: reg_num=%0d ext_reg=%0d",
r_x.register_num, r_x.ext_register_num), UVM_NONE)

      if(header_dw == 3) begin
  r_x.addr = r_x.tlp_q[2];
end
else if(header_dw == 4) begin
  r_x.addr = {r_x.tlp_q[2], r_x.tlp_q[3][31:2], 2'b00};
end

    ////////////////////////////// PAYLOAD //////////////////////////////
    payload_dw = r_x.length;
 `uvm_info("TLP_length",
        $sformatf("[%s] ERR_LENGTH: Expected payload = %0d DW, Captured payload = %0d DW, Missing = %0d DW - Malformed TLP",
                   tag, payload_dw, actual_payload_dw, payload_dw - actual_payload_dw),UVM_LOW)

    if(r_x.fmt inside {3'b010, 3'b011}) begin
      r_x.payload = new[payload_dw];
      for(int i = 0; i < payload_dw; i++) begin
        //-------------------------------------------------------------
        // Check exactly one clock for payload DW #i - no waiting/
        // retrying. If valid&&ready isn't there on this very edge,
        // the sender has stopped sending early (as seen in the log:
        // header promised 12 DW, only 9 ever arrived) - break out
        // immediately instead of blocking. This lets actual_payload_dw
        // reflect the true captured count and lets the ERR_LENGTH /
        // malformed_length checker below actually run and drop the
        // packet, instead of the thread hanging forever.
        //-------------------------------------------------------------
        @(posedge RX_TL_DL.CLK);
        if (RX_TL_DL.tl_rx_valid && RX_TL_DL.tl_rx_ready) begin
          dw = RX_TL_DL.tl_rx_data;
          r_x.payload[i] = dw;
          r_x.tlp_q.push_back(dw);
          actual_payload_dw++;
        end else begin
          `uvm_info("TLP_length",
            $sformatf("[%s] Payload DW #%0d not present - stopping early after %0d/%0d DW captured",
                       tag, i, actual_payload_dw, payload_dw), UVM_LOW)
          break;
        end
      end
    end

    `uvm_info("TLP_length",
        $sformatf("[%s] ERR_LENGTH: Expected payload = %0d DW, Captured payload = %0d DW, Missing = %0d DW - Malformed TLP",
                   tag, payload_dw, actual_payload_dw, payload_dw - actual_payload_dw),UVM_LOW)

    //-----------------------------------------------------------
    // ERR_LENGTH checker: Length field in the header must match
    // the number of payload DWs actually captured on the bus.
    // This is latched into malformed_length and used below to
    // DROP the packet before it reaches RX_PCIe_LUT / the
    // scoreboard - previously the uvm_error was raised here but
    // the packet was still written downstream, so a length-
    // mismatched (malformed) TLP could still be silently scored
    // as a PASS by the scoreboard.
    //-----------------------------------------------------------
    malformed_length = (r_x.fmt inside {3'b010, 3'b011}) && (actual_payload_dw != payload_dw);

    if (malformed_length) begin
      `uvm_error("MALFORMED_TLP",
        $sformatf("[%s] ERR_LENGTH: Expected payload = %0d DW, Captured payload = %0d DW, Missing = %0d DW - Malformed TLP - PACKET DROPPED, not forwarded to LUT/Scoreboard",
                   tag, payload_dw, actual_payload_dw, payload_dw - actual_payload_dw))
    end


    ////////////////////////////// ECRC CHECK //////////////////////////////
    if(r_x.td) begin
      do begin
        @(posedge RX_TL_DL.CLK);
      end while(!(RX_TL_DL.tl_rx_valid && RX_TL_DL.tl_rx_ready));
      dw = RX_TL_DL.tl_rx_data;
      r_x.ECRC = dw;

      calculated_ecrc = r_x.calculate_ecrc();

      `uvm_info("RX_TL_MONITOR", $sformatf("[%s] RX ECRC CHECK: RECEIVED=%08h CALCULATED=%08h", tag, r_x.ECRC, calculated_ecrc), UVM_LOW)

      if(calculated_ecrc == r_x.ECRC) begin
        r_x.ecrc_error   = 1'b0;
        r_x.compl_status = 3'b000;
        r_x.tlp_q.push_back(r_x.ECRC);

        foreach(r_x.tlp_q[i])
          `uvm_info("RX_TL_MONITOR", $sformatf("[%s] RX_TLP[%0d] = %08h @ %0t", tag, i, r_x.tlp_q[i], $time), UVM_LOW)
 if(r_x.ep ==1)
        `uvm_error("RX_TL_MONITOR", $sformatf("[%s] POISONED TLP - PACKET DROPPED", tag))
      else if(malformed_length)
        `uvm_error("RX_TL_MONITOR", $sformatf("[%s] MALFORMED TLP (length mismatch) - PACKET DROPPED", tag))
      else begin

        RX_TL_Send.write(r_x);
	`uvm_info("MON_TO_LUT",
$sformatf("Sending to LUT: reg=%0d tag=%0d",
          r_x.register_num,
          r_x.tag),
UVM_NONE)
        RX_TL_MON_Send.write(r_x);

      end 
      end 
      else begin
        r_x.ecrc_error = 1'b1;
        `uvm_error("RX_TL_MONITOR", $sformatf("[%s] ECRC MISMATCH - PACKET DROPPED", tag))
      end

    end else begin
      r_x.ecrc_error   = 1'b0;
      r_x.compl_status = 3'b000;
      if(r_x.ep ==1)
        `uvm_error("RX_TL_MONITOR", $sformatf("[%s] POISONED TLP - PACKET DROPPED", tag))
      else if(malformed_length)
        `uvm_error("RX_TL_MONITOR", $sformatf("[%s] MALFORMED TLP (length mismatch) - PACKET DROPPED", tag))
      else begin
      foreach(r_x.tlp_q[i])
        `uvm_info("RX_TL_MONITOR", $sformatf("[%s] RX_TLP[%0d] = %08h @ %0t", tag, i, r_x.tlp_q[i], $time), UVM_LOW)

      RX_TL_Send.write(r_x);
      RX_TL_MON_Send.write(r_x);
      end
          end

    wait(RX_TL_DL.tl_rx_valid == 0);

  endtask : ep_collecting_tx_request


  task ep_sending_rx_completion(Sequence_item t_x);

    bit [31:0] dw;
    int header_dw;
    int payload_length;

    ////////////////////////////// HEADER DW0 //////////////////////////////
    do begin
      @(posedge RX_TL_DL.CLK);
    end while(!(RX_TL_DL.tl_tx_valid && RX_TL_DL.tl_tx_ready));

    dw = RX_TL_DL.tl_tx_data;

    t_x.tlp_q.delete();
    t_x.tlp_q.push_back(dw);

    t_x.fmt    = dw[31:29];
    t_x.r_type = dw[28:24];
    t_x.length = dw[9:0];
    t_x.td     = dw[15];
     case(t_x.r_type)
      5'b00000 :
        if(t_x.fmt inside {3'b000, 3'b001})
          t_x.e_type = MEM_RD;
        else
          t_x.e_type = MEM_WR;

      5'b00010 :
        if(t_x.fmt == 3'b000)
          t_x.e_type = IO_RD;
        else
          t_x.e_type = IO_WR;

      5'b00100 :
        if(t_x.fmt == 3'b000)
          t_x.e_type = CFG_RD0;
        else
          t_x.e_type = CFG_WR0;

      5'b00101 :
        if(t_x.fmt == 3'b000)
          t_x.e_type = CFG_RD1;
        else
          t_x.e_type = CFG_WR1;

      5'b01010 :
        if(t_x.fmt == 3'b000)
          t_x.e_type = CPL;
        else if (t_x.fmt==3'b010)
          t_x.e_type = CPL_DATA;

    endcase




    // header DW count
    case(t_x.fmt)
      3'b000, 3'b010 : header_dw = 3;
      3'b001, 3'b011 : header_dw = 4;
      default         : header_dw = 3;
    endcase

    ////////////////////////////// REMAINING HEADER //////////////////////////////
    for(int i = 1; i < header_dw; i++) begin
      do begin
        @(posedge RX_TL_DL.CLK);
      end while(!(RX_TL_DL.tl_tx_valid && RX_TL_DL.tl_tx_ready));
      dw = RX_TL_DL.tl_tx_data;
      t_x.tlp_q.push_back(dw);
    end
 t_x.req_id       = t_x.tlp_q[2][31:16];
    t_x.tag          = t_x.tlp_q[2][15:8];
    t_x.lower_addr   = t_x.tlp_q[2][6:0];
    t_x.completer_id = t_x.tlp_q[1][31:16];
    t_x.compl_status = t_x.tlp_q[1][15:13];
    t_x.bcm          = t_x.tlp_q[1][12];
    t_x.byte_count   = t_x.tlp_q[1][11:0];

    ////////////////////////////// PAYLOAD //////////////////////////////
    payload_length = t_x.length;

    if(t_x.fmt inside {3'b010, 3'b011}) begin
      t_x.payload = new[payload_length];
      for(int i = 0; i < payload_length; i++) begin
        do begin
          @(posedge RX_TL_DL.CLK);
        end while(!(RX_TL_DL.tl_tx_valid && RX_TL_DL.tl_tx_ready));
        dw = RX_TL_DL.tl_tx_data;
        t_x.payload[i] = dw;
        t_x.tlp_q.push_back(dw);
      end
    end

    ////////////////////////////// ECRC //////////////////////////////
    if(t_x.td) begin
      do begin
        @(posedge RX_TL_DL.CLK);
      end while(!(RX_TL_DL.tl_tx_valid && RX_TL_DL.tl_tx_ready));
      dw = RX_TL_DL.tl_tx_data;
      t_x.ECRC = dw;
      t_x.tlp_q.push_back(dw);
    end

    foreach(t_x.tlp_q[i])
      `uvm_info("RX_TL_MONITOR", $sformatf("[%s] TL_RX_MONITOR_TLP_PACKET[%0d] = %0h @(%0t)", tag, i, t_x.tlp_q[i], $time), UVM_LOW)

    RX_TL_Send.write(t_x);

    wait(RX_TL_DL.tl_tx_valid == 0);

  endtask : ep_sending_rx_completion

endclass : PCIe_TL_Monitor
