interface pipe_tx_interface(input bit PCLK, input bit RESET);
  logic        dl_mac_packet;
  logic        tl_mac_packet;
  logic TxDataValid;
  logic[129:0] TxData;
  logic TxDataK;
  logic TxDetectRx;
  logic TxElecIdle;
  logic [129:0] RxData;
  logic RxDataK;
  logic RxValid;
  logic RxElecIdle;
  logic PhyStatus;
  logic [2:0] RxStatus;
  logic [2:0] PowerDown;
  logic [2:0] PCLK_Rate;
  logic [1:0] Rate;
  logic RxWidth;
  logic TxWidth;
  logic DataBusWidth;
endinterface
